version: '2.1'
services:
  spark-master:
    build:
        context: /home/ubuntu/project
        dockerfile: master.Dockerfile
    hostname: sparkmaster
    ports:
        - "7077:7077"
  spark-worker-1:
    build:
        context: /home/ubuntu/project/workersdf
        dockerfile: worker1.Dockerfile
    ports:
        - "8001:8001"
    depends_on:
        - spark-master